name: ansible-lint
on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["*"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6

      - name: Notify discord
        uses: th0th/notify-discord@v0.4.1
        if: ${{ always() }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_LINT }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: ${{ github.event.repository.name }}
          GITHUB_JOB_STATUS: ${{ job.status }}
